Kotlin. Homework #2
mawekk/shallowSizeTemplate pull request #1
Opened 2022-03-27 16:12 UTC by mawekk

2022-03-31 17:25 UTC, illided requested changes

2022-03-31 17:25 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                 |""".`class`
Кажется `trimMargin()` забыли

2022-03-31 17:25 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                 |""".`class`
И давай это впринципе как нибудь приведем к более читабельному виду)

2022-03-31 17:25 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                 |  fun shallowSize(): Int = TODO()
Хочется какую нибудь внятную ошибку в случае чего)

2022-03-31 17:25 UTC, illided commented on .github/workflows/main.yaml
> +        run: ./gradlew detekt
Меня попросили докапываться до стоковых CI и detekt :(
Давай это как нибудь приукрасим например с помощью [тест репортов](https://github.com/actions/upload-artifact)

2022-04-13 15:30 UTC, illided approved these changes
Все ок. Кидаю тебя в Настю

2022-04-19 07:47 UTC, nbirillo requested changes

2022-04-19 07:47 UTC, nbirillo commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                       |    fun shallowSize(): Int = TODO("body will be added later")
А сделай более информативную ошибку, представь, что ты пользователь и тебе прилетает такое сообщение. В нем даже не говорится у какой функции body будет добавлено

2022-04-19 07:47 UTC, nbirillo commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                            ?: throw NoSuchElementException()
Кидать ошибки пустые не очень классно, добавь информативное сообщение

2022-04-19 07:47 UTC, nbirillo commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                        clazz.functions.find { it.name.toString() == "shallowSize" && it.valueParameters.isEmpty() }
А еще shallowSize можно вынести в константу и использовать в обоих местах

2022-05-02 09:52 UTC, nbirillo approved these changes

2022-05-02 09:52 UTC, merged